import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{settle,reconcile,sendOutbox} from '../src/worker.js';
import {PACKAGES,candidates,validateBooking,verifySignature,checkoutBody,calendarFile} from '../src/core.js';

const envBase={TIME_ZONE:'America/Mexico_City',START_HOUR:'9',END_HOUR:'17',DAYS:'0,1,2,3,4,5,6',BOOKING_ENABLED:'true',PUBLIC_ORIGIN:'https://booking.example.com',TURNSTILE_SITE_KEY:'test',TURNSTILE_SECRET_KEY:'test',STRIPE_SECRET_KEY:'sk_test_fake',STRIPE_WEBHOOK_SECRET:'whsec_test',RESEND_API_KEY:'test',EMAIL_FROM:'Ubaman <test@example.com>',COACH_EMAIL:'coach@example.com',ADMIN_TOKEN:'x'.repeat(40)};
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));return {raw:db,prepare(q){let args=[];const stmt={bind(...values){args=values;return stmt;},async first(){return db.prepare(q).get(...args)||null;},async all(){return {results:db.prepare(q).all(...args)};},async run(){return {meta:db.prepare(q).run(...args)};}};return stmt;},async batch(statements){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};}
function setup(){return {...envBase,DB:database()};}
const ctx={waitUntil(){}};
function req(path,data,headers={}){return new Request(envBase.PUBLIC_ORIGIN+'/api/'+path,{method:data?'POST':'GET',headers:{Origin:envBase.PUBLIC_ORIGIN,'Content-Type':'application/json',...headers},body:data?JSON.stringify(data):undefined});}
const input=(slots,q=1)=>({quantity:q,slots,name:'Cliente Prueba',email:'client@example.com',challenge:'test'});
function paymentMock({timeout=false}={}){let calls=0,session,body;return {get calls(){return calls;},get session(){return session;},get body(){return body;},fetch:async(url,options)=>{if(url.includes('siteverify'))return Response.json({success:true,hostname:'booking.example.com',action:'booking'});if(url.includes('stripe.com')){calls++;if(!session){body=new URLSearchParams(options.body);session={id:'cs_test_'+crypto.randomUUID(),url:'https://checkout.stripe.com/test',status:'open',payment_status:'unpaid',mode:'payment',currency:'usd',amount_total:Number(body.get('line_items[0][price_data][unit_amount]')),metadata:{order_id:body.get('metadata[order_id]')}};}if(timeout&&calls===1)throw new Error('network timeout after creation');return Response.json(session);}return Response.json({id:'email_test'});}};}

test('prices and booking validation reject tampering, duplicate or insufficient dates',()=>{const env=setup(),slots=candidates(env);assert.deepEqual(PACKAGES,{1:4000,3:9600,5:16000});assert.equal(validateBooking({...input([slots[0].start]),amount:1},env).amount,4000);assert.throws(()=>validateBooking(input([slots[0].start,slots[0].start,slots[1].start],3),env));assert.throws(()=>validateBooking(input([slots[0].start],5),env));assert.throws(()=>validateBooking(input([1]),env));});
test('schedule respects local hours, notice, buffer, and horizon across DST',()=>{for(const zone of ['America/Mexico_City','America/Hermosillo','America/New_York']){const now=Date.parse('2026-10-30T12:00:00Z')/1000;const slots=candidates({...envBase,TIME_ZONE:zone},now);assert.ok(slots.length>0);for(const s of slots){assert.ok(s.start>=now+7200);const hour=Number(new Intl.DateTimeFormat('en',{timeZone:zone,hour:'numeric',hourCycle:'h23'}).format(new Date(s.start*1000)));assert.ok(hour>=9&&hour<=16);assert.ok(s.day<='2026-11-13');}}});
test('Stripe signature rejects forged and stale messages',async()=>{const raw='{"ok":true}',now=10000,key=await crypto.subtle.importKey('raw',new TextEncoder().encode('secret'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${now}.${raw}`))).toString('hex');assert.equal(await verifySignature(raw,`t=${now},v1=${sig}`,'secret',now),true);assert.equal(await verifySignature(raw+' ',`t=${now},v1=${sig}`,'secret',now),false);assert.equal(await verifySignature(raw,`t=${now},v1=${sig}`,'secret',now+301),false);});
test('checkout uses server amount and calendar has one UTC event per session',()=>{const order={id:'test',token:'token',email:'a@example.com',quantity:3,amount:9600,expires:10000,created:1000};const body=new URLSearchParams(checkoutBody(order,envBase.PUBLIC_ORIGIN));assert.equal(body.get('line_items[0][price_data][unit_amount]'),'9600');assert.equal(body.get('payment_method_types[0]'),'card');const ics=calendarFile(order,[{start:10000},{start:20000},{start:30000}]);assert.equal(ics.match(/BEGIN:VEVENT/g).length,3);assert.match(ics,/DTSTART:19700101T024640Z/);});
test('schema prevents overlap and fourth session; rollback is all-or-nothing',async()=>{const env=setup(),db=env.DB;db.raw.exec("INSERT INTO orders(id,token,name,email,amount,quantity,status,created,expires,checkout_body) VALUES('o','t','a','e',16000,5,'creating',0,0,'')");for(let i=0;i<3;i++)await db.prepare('INSERT INTO slots VALUES(?,?,?,1)').bind('o',10000+i*5400,'2026-09-15').run();await assert.rejects(db.prepare('INSERT INTO slots VALUES(?,?,?,1)').bind('o',26200,'2026-09-15').run());await assert.rejects(db.prepare('INSERT INTO slots VALUES(?,?,?,1)').bind('o',10001,'2026-09-16').run());await assert.rejects(db.batch([db.prepare("INSERT INTO blocked_days VALUES('2026-09-20')"),db.prepare('INSERT INTO slots VALUES(?,?,?,1)').bind('o',10000,'2026-09-15')]));assert.equal(db.raw.prepare('SELECT count(*) n FROM blocked_days').get().n,0);});
test('package selection commits all slots, duplicate purchase cannot claim them',async()=>{const env=setup(),mock=paymentMock();const original=globalThis.fetch;globalThis.fetch=mock.fetch;try{const slots=candidates(env).filter((s,i)=>i%5===0).slice(0,5).map(s=>s.start);const r=await worker.fetch(req('book',input(slots,5)),env,ctx);assert.equal(r.status,200);assert.equal(mock.body.get('line_items[0][price_data][unit_amount]'),'16000');assert.equal(env.DB.raw.prepare('SELECT count(*) n FROM slots').get().n,5);assert.equal((await worker.fetch(req('book',input(slots,5)),env,ctx)).status,409);assert.equal(env.DB.raw.prepare('SELECT count(*) n FROM orders').get().n,1);}finally{globalThis.fetch=original;}});
test('forged webhook and wrong origin never create or confirm reservations',async()=>{const env=setup();assert.equal((await worker.fetch(req('webhook',{type:'checkout.session.completed'}),env,ctx)).status,400);assert.equal((await worker.fetch(req('book',{} ,{Origin:'https://evil.example'}),env,ctx)).status,403);assert.equal((await worker.fetch(req('admin'),env,ctx)).status,401);});
test('network ambiguity retains locks; reconciliation recovers the same checkout',async()=>{const env=setup(),mock=paymentMock({timeout:true}),original=globalThis.fetch;globalThis.fetch=mock.fetch;try{const slot=candidates(env)[0].start;const r=await worker.fetch(req('book',input([slot])),env,ctx);assert.equal(r.status,202);assert.equal(env.DB.raw.prepare('SELECT active FROM slots').get().active,1);await reconcile(env);const order=env.DB.raw.prepare('SELECT * FROM orders').get();assert.equal(order.status,'pending');assert.equal(order.checkout_id,mock.session.id);assert.equal(mock.calls,2);}finally{globalThis.fetch=original;}});
test('paid webhook is idempotent, outbox sends separately once, expired event cannot free paid slot',async()=>{const env=setup(),mock=paymentMock(),original=globalThis.fetch;globalThis.fetch=mock.fetch;try{await worker.fetch(req('book',input([candidates(env)[0].start])),env,ctx);const order=env.DB.raw.prepare('SELECT * FROM orders').get(),session={...mock.session,status:'complete',payment_status:'paid'};await settle(env,order,session);await settle(env,order,session);assert.equal(env.DB.raw.prepare('SELECT status FROM orders').get().status,'paid');assert.equal(env.DB.raw.prepare('SELECT count(*) n FROM outbox').get().n,2);await sendOutbox(env);await sendOutbox(env);assert.equal(env.DB.raw.prepare('SELECT sum(attempts) n FROM outbox').get().n,2);await settle(env,order,{...session,status:'expired'});assert.equal(env.DB.raw.prepare('SELECT active FROM slots').get().active,1);}finally{globalThis.fetch=original;}});
test('wrong amount holds order for review without emailing; expired checkout frees capacity',async()=>{for(const mismatch of [true,false]){const env=setup(),mock=paymentMock(),original=globalThis.fetch;globalThis.fetch=mock.fetch;try{await worker.fetch(req('book',input([candidates(env)[0].start])),env,ctx);const order=env.DB.raw.prepare('SELECT * FROM orders').get();await settle(env,order,{...mock.session,status:mismatch?'complete':'expired',payment_status:mismatch?'paid':'unpaid',amount_total:1});assert.equal(env.DB.raw.prepare('SELECT status FROM orders').get().status,mismatch?'review':'expired');assert.equal(env.DB.raw.prepare('SELECT active FROM slots').get().active,mismatch?1:0);assert.equal(env.DB.raw.prepare('SELECT count(*) n FROM outbox').get().n,0);}finally{globalThis.fetch=original;}}});
test('blocking a date excludes it and rejects checkout on that date',async()=>{const env=setup(),mock=paymentMock(),original=globalThis.fetch;globalThis.fetch=mock.fetch;try{const slot=candidates(env)[0];await env.DB.prepare('INSERT INTO blocked_days VALUES(?)').bind(slot.day).run();const r=await worker.fetch(req('slots'),env,ctx);assert.ok(!(await r.json()).slots.some(s=>s.day===slot.day));assert.equal((await worker.fetch(req('book',input([slot.start])),env,ctx)).status,409);}finally{globalThis.fetch=original;}});
